name: Dotnet Core CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Allows manual trigger from GitHub Actions

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # Skipping the build step here

      - name: Run Unit Tests
        run: dotnet test --configuration Release --verbosity normal

  deploy:
    name: Deploy (Artifact Output)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Publish Project
        run: dotnet publish -c Release -o ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PublishedApp
          path: ./publish
